---
- name: Install roles
  vars_files:
    - vars.yml
  hosts: all
  pre_tasks:
    - name: Remove ca-certificates
      apt:
        name: ca-certificates
        state: absent
    - name: Ensure reinstall ca-certificates
      apt:
        name: ca-certificates
        state: present
        update_cache: yes
  roles:
    - role: geerlingguy.pip
    - role: nginxinc.nginx
    - role: geerlingguy.mysql
    - role: geerlingguy.java
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.gogs
    - role: geerlingguy.jenkins
    - role: phabricator
  tasks:
    - name: Configuration nginx conf for jenkins
      template:
        src: '{{ item.src}}'
        dest: '{{ item.dest }}'
      with_items:
        - src: templates/jenkins.conf.j2
          dest: /etc/nginx/conf.d/{{ jenkins_url }}.conf
        - src: templates/gogs.conf.j2
          dest: /etc/nginx/conf.d/{{ gogs_url }}.conf
      notify: restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
