- src: geerlingguy.gogs
  
- src: geerlingguy.java

- src: geerlingguy.jenkins

- src: geerlingguy.pip

# - src: geerlingguy.nginx

- src: nginxinc.nginx

- src: geerlingguy.mysql

- src: geerlingguy.php

- src: geerlingguy.php-mysql

- src: geerlingguy.php-versions
