---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: 'Update apt cache (on Debina)'
      apt:
        name: gpg-agent
        state: present
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debina'
- import_playbook: ../../playbook.yml
